FROM node:18.18-alpine3.17
USER root

RUN apk --no-cache add \
    bash \
    curl \
    docker-cli

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

CMD ["npm", "start", "--", "--env-file", ".env"]