FROM node:18.18-alpine3.17
USER root

RUN apk --no-cache add \
    bash \
    curl \
    docker-cli \
    firefox

WORKDIR /app

COPY package*.json ./

RUN npm install && npm install --save-dev jest-junit

COPY . .

CMD ["npm", "run", "start", "--", "--env-file", ".env"]