name: MERN CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # or your desired version

    - name: Install dependencies for backend
      run: |
        cd services/backend
        npm install
        
    - name: Install dependencies for frontend
      run: |
        cd services/frontend
        npm install

   # Uncomment below if you have tests to run for backend
    # - name: Test backend
    #   run: |
    #     cd services/backend
    #     npm test
    #   env:
    #     BASE_URL: ${{ secrets.BASE_URL }}
    #     GMAIL_USER: ${{ secrets.GMAIL_USER }}
    #     MONGODB_CONNECTION_STRING: ${{ secrets.MONGODB_CONNECTION_STRING }}
    #     OAUTH_CLIENT_ID: ${{ secrets.OAUTH_CLIENT_ID }}
    #     OAUTH_CLIENT_SECRET: ${{ secrets.OAUTH_CLIENT_SECRET }}
    #     OAUTH_PROVIDER_URL: ${{ secrets.OAUTH_PROVIDER_URL }}
    #     OAUTH_REFRESH_TOKEN: ${{ secrets.OAUTH_REFRESH_TOKEN }}

    # Uncomment below if you have tests to run for frontend
    # - name: Test frontend
    #   run: |
    #     cd services/frontend
    #     npm test
